---

# The cloud provider
# (also embedded in the the file names of the tasks we'll run)
provider: openstack

exec_base_name: pulsar-exec-node-
exec_type: l1.6xl
exec_image_name: vggp-v31-j124
exec_count: 25
exec_offset: 5

create_exec_instances: no
