---

- name: Update all packages
  yum:
    name: "*"
    state: latest
    update_cache: yes

- name: Install GPU/CUDA Material
  block:

  - name: Install nvida Docker repo
    shell: curl {{ src }} > {{ dst }}
    vars:
      src: https://nvidia.github.io/nvidia-docker/centos7/nvidia-docker.repo
      dst: /etc/yum.repos.d/nvidia-docker.repo

  - name: Install cuda
    package:
      name: "{{ item }}"
      state: present
    loop:
    - cuda-11-2
    - nvidia-container-toolkit

  - name: Run Nvidia container test
    command: docker run --gpus all nvidia/cuda:11.0-base nvidia-smi

  when:
  - exec_is_gpu|bool
  - install_gpu_cuda|bool

- name: Set condor_config.local
  template:
    src: condor_config.local.j2
    dest: /etc/condor/condor_config.local
    owner: root
    group: root
    mode: '0644'
  notify: Restart services

- name: Set data.autofs
  template:
    src: data.autofs.j2
    dest: /etc/auto.master.d/data.autofs
    owner: root
    group: root
    mode: '0644'
  notify: Restart services

- name: Set auto.data
  template:
    src: auto.data.j2
    dest: /etc/auto.data
    owner: root
    group: root
    mode: '0644'
  notify: Restart services
