---

# Creates our cluster on OpenStack.
#
# This is driven by variables that should be defined by
# 'sourcing' your OpenStack Keystone file. The initial
# 'assert' checks that these variables are set.

- name: Assert cloud variables
  assert:
    that:
    - os_auth_url is defined
    - exec_count > 0

# Create the exec nodes but, as before, we allow for failure.
# We give up if, after 5 attempts, we cannot create an instance.

- name: Display exec node flavour
  debug:
    var: exec_type

- name: Display exec node count and offset
  debug:
    msg: exec_count={{ exec_count }} exec_offset={{ exec_offset }}

- name: Create exec nodes (batch)
  script: >-
    create-os-server.py --name {{ exec_base_name }}
    --flavour {{ exec_type }}
    --image {{ exec_image_name }}
    --keypair pulsar-cloud_key
    --network {{ exec_network }}
    --wait-time {{ os_server_wait_time_s }}
    --count {{ exec_count }}
    --offset {{ exec_offset }}
    --suffix .xchem
    --sgs pulsar-egress-public pulsar-ingress-private
    --verbose
  environment:
    OS_AUTH_URL: "{{ os_auth_url }}"
    OS_PROJECT_ID: "{{ os_project_id }}"
    OS_USERNAME: "{{ os_username }}"
    OS_PASSWORD: "{{ os_password }}"
    OS_USER_DOMAIN_NAME: "{{ os_user_domain_name }}"
    OS_REGION_NAME: "{{ os_region_name }}"
  register: workers
  changed_when: "'Cloud changed: True' in workers.stdout"

- name: Display 'create exec nodes' output
  debug:
    msg: "{{ item }}"
  loop: "{{ workers.stdout_lines }}"
