---

- name: Assert key variables
  assert:
    that: os_auth_url is defined

# Get information about the exec nodes.
# Nodes gathered must begin with "{{ exec_base_name }}-[0-9]"
# We simply want their IP addresses
# so we can add them to the 'servers' inventory group

- name: Get exec node facts
  os_server_facts:
    auth: "{{ os_auth }}"
    region_name: "{{ os_region_name }}"
    server: "{{ exec_base_name }}-[0-9]*"

- name: Adjust exec node group
  add_host:
    groups: exec
    name: "{{ item.private_v4 }}"
  loop: "{{ openstack_servers }}"
  no_log: yes
  changed_when: false
