---

- name: Display exec node name
  debug:
    msg: exec_base_name={{ exec_base_name }} create_exec_instances={{ create_exec_instances }}

- include_tasks: create-{{ provider }}-instances.yaml
  when: create_exec_instances|bool

- include_tasks: gather-{{ provider }}-facts.yaml
